exec sp_rename 'TRUONGHOC_DIEMDANH.NGUOITAODD_ID', 'NGUOITAODD_ID__U26453', 'COLUMN' ^
alter table TRUONGHOC_DIEMDANH drop constraint FK_TRUONGHOC_DIEMDANH_ON_NGUOITAODD ;
drop index IDX_TRUONGHOC_DIEMDANH_ON_NGUOITAODD on TRUONGHOC_DIEMDANH ;
alter table TRUONGHOC_DIEMDANH add NGUOITAODD nvarchar(255) ;
